# Generated by Django 3.1.7 on 2021-03-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='slug',
        ),
    ]
