# Generated by Django 3.1.7 on 2021-03-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_productfeature_productfeaturevalidators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfeature',
            old_name='filter_measure',
            new_name='feature_value',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='user_in_filter',
        ),
        migrations.AddField(
            model_name='product',
            name='product_feature',
            field=models.ManyToManyField(related_name='product_features', to='mainapp.ProductFeature'),
        ),
    ]
