# Generated by Django 3.1.7 on 2021-03-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210314_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeaturevalue',
            name='category',
        ),
        migrations.AlterField(
            model_name='productfeaturevalue',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='mainapp.productfeaturename'),
        ),
    ]
