# Generated by Django 3.1.7 on 2021-03-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210316_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeaturename',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature_names', to='mainapp.category'),
        ),
    ]
