# Generated by Django 3.1.7 on 2021-03-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210227_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
